### ISSUE TITLE
don't receive WOU from stream

### ISSUE THREAD

**Issue by firebird631** [ig-python/trading-ig#257]
From stream I receive OPU and CONFIRMS but never WOU events.

How did you process to determine if it is a market position that is created or a working (limit) order ?

Did you ever received some WOU event (demo, prod) ?

**Comment by bug-or-feature** [comment]
@firebird631 did you resolve this issue? I'll close if no response

**Comment by firebird631** [comment]
@bug-or-feature not really fixed, proceed differently.

**Comment by bug-or-feature** [comment]
@firebird631 ok thanks, I'm closing then. Note that the [latest release](https://github.com/ig-python/trading-ig/releases/tag/0.0.21) adds support for the official Lightstreamer Python client SDK. That means if there are any low level streaming issues, they can be directed towards people who can help
