### ISSUE TITLE
IG Rest API gives error.security.client-token-invalid after 13-14 hours of continuous usage

### ISSUE THREAD

**Issue by MilindRCodes** [ig-python/trading-ig#268]
I observed that the IG Rest API gives the **error.security.client-token-invalid** error after 13-14 hours of continuous usage in the demo account. 

I would appreciate guidance on possible ways to overcome this error.

Thank you.

**Comment by bug-or-feature** [comment]
https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem

**Comment by galburn** [comment]
I don't experience this issue.  Can you please detail exactly how you see it?

**Comment by MilindRCodes** [comment]
@galburn 

I put it on a continuous run using the demo account and after 13-14 hours, I got this error, 

I tested it twice and got this error everytime.

**Comment by galburn** [comment]
I don't see this issue at all.  My code runs all week without a problem.  Can you put up the code?  Particularly which version of the login calls you are using.  Ideally, a minimal code version that shows the issue.

**Comment by bug-or-feature** [comment]
No updates or responses, closing
