### ISSUE TITLE
expand_columns() returning nan instead of None.

### ISSUE THREAD

**Issue by oliverpolden** [ig-python/trading-ig#278]
IG returns data with "None" e.g. limitLevel: None.

I've found that fetch_open_positions() now returns nan when a limitLevel comes in as None.

I've seen: `na_action='ignore'`. Changing that to `na_action=None` doesn't appear to fix it.

Strangely, other fields, trailingStep for example, do end up as None.

**Comment by bug-or-feature** [comment]
https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem
