### ISSUE TITLE
ig_service.search_markets(search_term) provides Exception: validation.null-not-allowed.epics

### ISSUE THREAD

**Issue by Leotheone** [ig-python/trading-ig#284]
I get the following strange error when I execute the search_market function :

tests/test_ig_service.py:None (tests/test_integration.py)
test_integration.py:349: in <module>
     test_search_markets()
test_integration.py:349: in test_ig_service
    response = ig_service.search_markets(search_term)
..\..\..\..\..\AppData\Local\Programs\Python\Python310\lib\site-packages\trading_ig\rest.py:1360: in search_markets
    data = self.parse_response(response.text)
..\..\..\..\..\AppData\Local\Programs\Python\Python310\lib\site-packages\trading_ig\rest.py:342: in parse_response_with_exception
    raise (Exception(response["errorCode"]))
E   Exception: validation.null-not-allowed.epics

**Comment by bug-or-feature** [comment]
https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem
