### ISSUE TITLE
conditional-set-value error when trying to add a SL distance when opening new position

### ISSUE THREAD

**Issue by vlecot** [ig-python/trading-ig#285]
Hello, 

I have been using trading-ig in my python script to open positions for a few months and encounter an issue lately when trying to open a position on CFD with the rest api with a stop loss. If i specify a number in stop_distance i get the following error from IG API : 

{"errorCode":"validation.target-value-conditional-set-value.request"}

Below is an exemple of the rest request : 

`resp = ig_service.create_open_position(
        currency_code='EUR',
        direction='BUY',
        epic='IX.D.SPTRD.IFE.IP',
        order_type='MARKET',
        expiry='-',
        force_open='false',
        guaranteed_stop='false',
        size='10', 
        level=None,
        limit_distance=None,
        limit_level=None,
        quote_id=None,
        stop_level=None,
        stop_distance='100',
        trailing_stop=None,
        trailing_stop_increment=None)`

It works perfectly fine if I leave None for stop_distance so the issue is really with this field. 
It tried storing the value in a variable, such as distancesl and refer to is a string instead of inputing the raw value `(stop_distance=str(distancesl)` but it doesnt work either. 
I use the lastest version of trading-ig.

Any help will be appreciated
Thank you very much

**Comment by bug-or-feature** [comment]
https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem
