### ISSUE TITLE
fetch_historical_prices_by_epic_and_date_range : "puredeal:err:(none):403 Access forbidden!"

### ISSUE THREAD

**Issue by NathanCladiere** [ig-python/trading-ig#293]
Hi,

Thanks for the python lib.

I have some issue when i tried to get historical data:

i add a print to see the problem  in fetch_historical_prices_by_epic_and_date_range  :

```
print("Response text:", response.text)
data = self.parse_response(response.text)
```

and see :"puredeal:err:(none):403 Access forbidden!"

Any idea where it comes from ?

**Comment by bug-or-feature** [comment]
https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem
