### ISSUE TITLE
Future warning in trading_ig\rest.py

### ISSUE THREAD

**Issue by Leotheone** [ig-python/trading-ig#330]
Hello,

For all intents and purposes, since the latest library version upgrades, this causes futureWarnings in fetch_historical_prices_by_epic, fetch_historical_prices_by_epic_and_num_points and fetch_historical_prices_by_epic_and_date_range
 functions located in trading_ig\rest.py :

...\trading_ig\rest.py:1801: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` data["prices"] = data["prices"].fillna(value=np.nan)

...\trading_ig\rest.py:1823: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` data["prices"] = data["prices"].fillna(value=np.nan)

...\trading_ig\rest.py:1887: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)` data["prices"] = data["prices"].fillna(value=np.nan)
  
Best regards

**Comment by bug-or-feature** [comment]
Thanks for your interest in the project.

Please provide more information: what upgrades? what versions of which libraries are you using? etc

It is all documented [here](https://trading-ig.readthedocs.io/en/latest/faq.html#what-if-i-have-a-problem)

**Comment by femtotrader** [comment]
Related

https://github.com/pandas-dev/pandas/blob/a99fb7d054ee0831f1c00d8bea1b54e383185802/doc/source/whatsnew/v2.2.0.rst#deprecated-automatic-downcasting

https://github.com/pandas-dev/pandas/pull/54710

https://github.com/pandas-dev/pandas/pull/54261

**Comment by bug-or-feature** [comment]
@Leotheone thanks for the code snippet - but you missed the most important (crucial) bit of information - your pandas version. The warnings you are seeing are due to your use of Pandas 2.2.0 which was released in January 2024. That's why we ask for **dependencies and their versions** when creating an issue

@femtotrader thanks for the clarification

**Comment by bug-or-feature** [comment]
Closing, merged with #329
