### ISSUE TITLE
Problem in Opening Positions that has stop_level and limit level

### ISSUE THREAD

**Issue by mehmetcigerli** [ig-python/trading-ig#342]
Hello,
I was able to open positions on LIVE CFD with create_open_position method. Likewise was able to update it afterwards with update_open_positions(). However when I include the stop_level and limit level while opening the position I receive the following error.

IGException: {"errorCode":"validation.target-value-conditional-set-value.request"}

I put my code below. I tried supplying these levels both as string, int, and float. I also tried rounding them up for float cases.
They all failed.
I appreciate your help.
Many thanks in advance.

close_level = 8310
stop_loss = 0.0102
take_profit = 0.06
stop_level = np.round(close_level * (1-stop_loss))
profit_level = np.round(close_level * (1+take_profit))

resp = ig_service.create_open_position(
        currency_code='GBP',
        direction='BUY',
        epic='IX.D.ASX.IFS.IP',
        order_type='MARKET',
        expiry='-',
        force_open='false',
        guaranteed_stop='false',
        size=0.5, level=None,
        limit_distance=None,
        limit_level=profit_level,
        quote_id=None,
        stop_level=stop_level,
        stop_distance=None,
        trailing_stop=None,
        trailing_stop_increment=None)

resp

**Comment by galburn** [comment]
I don't have access to my test system at the moment, but from memory here are some tips.
* Either provide stop_distance or stop_level, never both.  Same for limit values.
* The API requires the numeric values as strings, but I think this is done automatically by the trading-ig library.
* Look in the API spec as it gives further guidance as to the validation performed.
Hope this helps

**Comment by mehmetcigerli** [comment]
Thank you @galburn,
I think I am doing the first, as in only levels are supplied, the distances are None.
I did try providing strings but this didnt solve the issue.

It is something else but havent been able to find out yet

**Comment by galburn** [comment]
Even "None" counts as a value.

**Comment by mehmetcigerli** [comment]
@galburn, hmmm, but it wants me to supply something for sure. I get this kind of error:

TypeError: create_open_position() missing 1 required positional argument: 'trailing_stop'

Maybe when you have access to your test system we can sort it out, I appreciate your help.

**Comment by mehmetcigerli** [comment]
@galburn thanks, I found the answer on here.
https://labs.ig.com/reference/positions-otc.html
When stop/limit level/distance is set, forec_open parameter should be 'true'.
I wrote it here in case someone else runs into same issue.

**Comment by galburn** [comment]
It would be helpful if the IG API would say what validation constraint is failing, but it doesn't.  As such, I don't think that any improvement can be made to trading-ig. 
@mehmetcigerli , Can you close this issue please?

**Comment by mehmetcigerli** [comment]
issue solved
